package com.myvideolibrary.app.security

import android.content.Context
import android.util.Base64
import dagger.hilt.android.qualifiers.ApplicationContext
import org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters
import org.bouncycastle.crypto.params.Ed25519PublicKeyParameters
import org.bouncycastle.crypto.signers.Ed25519Signer
import org.json.JSONObject
import java.security.SecureRandom
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Offline, device-bound activation — a Kotlin port of the shared Ed25519 license
 * scheme (same one the "حلالي" app uses), so codes generated by the same keygen
 * (same seed, same [PREFIX]) validate here too.
 *
 * The app embeds only the **public** key and verifies locally; no internet, and
 * the secret seed never ships. A code is a Base32 packet: 2 bytes duration
 * (days, big-endian; 0 = permanent) + a 64-byte Ed25519 signature over
 * `PREFIX|deviceId|days`. The owner can always unlock any device by entering the
 * secret seed (a global master key), so they can never be locked out.
 */
@Singleton
class LicenseManager @Inject constructor(
    @ApplicationContext private val context: Context
) {

    enum class State { DISABLED, NONE, ACTIVE, EXPIRED }

    private val prefs by lazy {
        context.getSharedPreferences("license", Context.MODE_PRIVATE)
    }

    // ---- Public API ----

    /** Stable per-install device number shown on the activation screen. */
    fun deviceId(): String {
        prefs.getString(KEY_DEVICE, null)?.takeIf { it.length >= 16 }?.let { return it }
        val raw = ByteArray(10).also { SecureRandom().nextBytes(it) }
        val id = base32Encode(raw)
        prefs.edit().putString(KEY_DEVICE, id).apply()
        return id
    }

    /** Device number formatted in groups of four for display. */
    fun deviceIdPretty(): String =
        deviceId().chunked(4).joinToString("-")

    fun state(): State {
        if (protectionDisabled()) return State.DISABLED
        val rec = readRecord() ?: return State.NONE
        val now = System.currentTimeMillis()
        // Clock guard: never let the effective time run backwards, so setting the
        // device clock back can't extend a time-limited licence.
        val eff = maxOf(now, rec.lastSeen)
        if (eff != rec.lastSeen) writeRecord(rec.copy(lastSeen = eff))
        if (rec.days == 0) return State.ACTIVE
        val expiry = rec.activatedAt + rec.days.toLong() * DAY_MS
        return if (eff < expiry) State.ACTIVE else State.EXPIRED
    }

    /** True when the user must activate before using the app. */
    fun needsActivation(): Boolean = when (state()) {
        State.ACTIVE, State.DISABLED -> false
        State.NONE, State.EXPIRED -> true
    }

    /** Days left for a time-limited licence, or null when permanent/none. */
    fun daysLeft(): Int? {
        val rec = readRecord() ?: return null
        if (rec.days == 0) return null
        val eff = maxOf(System.currentTimeMillis(), rec.lastSeen)
        val expiry = rec.activatedAt + rec.days.toLong() * DAY_MS
        return (((expiry - eff) + DAY_MS - 1) / DAY_MS).toInt().coerceAtLeast(0)
    }

    /** Validates an activation code and, on success, stores the licence. */
    fun tryActivate(code: String): Boolean {
        val days = verify(code) ?: return false
        writeRecord(Record(days, System.currentTimeMillis(), System.currentTimeMillis()))
        return true
    }

    /** Owner recovery: the secret seed (64 hex) unlocks permanently on any device. */
    fun recoverWithSeed(seedHex: String): Boolean {
        val h = seedHex.trim().lowercase().filter { it in "0123456789abcdef" }
        if (h.length != 64) return false
        return try {
            val seed = ByteArray(32) { h.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
            val pub = Ed25519PrivateKeyParameters(seed, 0).generatePublicKey().encoded
            val ours = Base64.decode(PUBLIC_KEY_B64, Base64.DEFAULT)
            if (pub.contentEquals(ours)) {
                writeRecord(Record(0, System.currentTimeMillis(), System.currentTimeMillis()))
                true
            } else false
        } catch (e: Exception) {
            false
        }
    }

    /** Re-locks the app without touching the user's library data. */
    fun deactivate() {
        prefs.edit().remove(KEY_LICENSE).apply()
    }

    // ---- Verification ----

    private fun verify(code: String): Int? {
        val pkt = base32Decode(normalize(code))
        if (pkt.size != 66) return null
        val days = ((pkt[0].toInt() and 0xFF) shl 8) or (pkt[1].toInt() and 0xFF)
        val sig = pkt.copyOfRange(2, 66)
        val msg = "$PREFIX|${deviceId()}|$days".toByteArray(Charsets.UTF_8)
        return try {
            val pub = Ed25519PublicKeyParameters(Base64.decode(PUBLIC_KEY_B64, Base64.DEFAULT), 0)
            val signer = Ed25519Signer().apply {
                init(false, pub)
                update(msg, 0, msg.size)
            }
            if (signer.verifySignature(sig)) days else null
        } catch (e: Exception) {
            null
        }
    }

    private fun protectionDisabled(): Boolean =
        PUBLIC_KEY_B64.isBlank() || PUBLIC_KEY_B64.startsWith("REPLACE_")

    // ---- Licence record persistence ----

    private data class Record(val days: Int, val activatedAt: Long, val lastSeen: Long)

    private fun readRecord(): Record? {
        val json = prefs.getString(KEY_LICENSE, null) ?: return null
        return try {
            val o = JSONObject(json)
            Record(o.getInt("d"), o.getLong("a"), o.getLong("s"))
        } catch (e: Exception) {
            null
        }
    }

    private fun writeRecord(rec: Record) {
        val json = JSONObject()
            .put("d", rec.days)
            .put("a", rec.activatedAt)
            .put("s", rec.lastSeen)
            .toString()
        prefs.edit().putString(KEY_LICENSE, json).apply()
    }

    // ---- Base32 (custom alphabet, identical to the keygen) ----

    private fun normalize(s: String): String =
        s.uppercase().filter { it in 'A'..'Z' || it in '0'..'9' }

    private fun base32Encode(bytes: ByteArray): String {
        var bits = 0
        var value = 0
        val out = StringBuilder()
        for (b in bytes) {
            value = (value shl 8) or (b.toInt() and 0xFF)
            bits += 8
            while (bits >= 5) {
                out.append(B32[(value ushr (bits - 5)) and 31])
                bits -= 5
            }
            value = value and ((1 shl bits) - 1)
        }
        if (bits > 0) out.append(B32[(value shl (5 - bits)) and 31])
        return out.toString()
    }

    private fun base32Decode(s: String): ByteArray {
        var bits = 0
        var value = 0
        val out = ArrayList<Byte>()
        for (c in s) {
            val k = B32.indexOf(c)
            if (k < 0) continue
            value = (value shl 5) or k
            bits += 5
            if (bits >= 8) {
                out.add(((value ushr (bits - 8)) and 0xFF).toByte())
                bits -= 8
            }
            value = value and ((1 shl bits) - 1)
        }
        return out.toByteArray()
    }

    companion object {
        /**
         * Public key (Base64). Replace with your own from `node keygen.mjs new`.
         * To share one licence across your apps ("universal"), use the SAME key
         * and prefix in each app.
         */
        const val PUBLIC_KEY_B64 = "7FjmkPiGy9/FUXc5nOnfGlrakC8qa68/zBDIp5fv5js="
        private const val PREFIX = "UNIV1"
        private const val B32 = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        private const val DAY_MS = 86_400_000L
        private const val KEY_DEVICE = "device_id"
        private const val KEY_LICENSE = "license_rec"
    }
}
